// Single source of truth for tag -> MSA Arabic title, rendered on /tags.
// Rule (AGENTS.md): any new tag introduced by a content batch MUST add its
// Arabic title to this map in the same change, or the tag renders
// English-only. Keep tag spelling identical across idea files so each
// sector shares one tag page.
export const tagArMap: Record<string, string> = {
  fintech: 'تكنولوجيا مالية',
  agritech: 'تكنولوجيا زراعية',
  logistics: 'لوجستيات وتوصيل',
  unicorn: 'شركات يونيكورن',
  failure: 'فشل',
  ecommerce: 'تجارة إلكترونية',
  proptech: 'تكنولوجيا عقارية',
  healthtech: 'تكنولوجيا صحية',
  diagnostics: 'تشخيص طبي',
  edtech: 'تعليم وتدريب',
  mobility: 'نقل ذكي',
  ai: 'ذكاء اصطناعي',
  marketplace: 'منصات وسيطة',
  climate: 'مناخ واستدامة',
  energy: 'طاقة ونفايات',
  b2b: 'تجارة بين الشركات',
  saas: 'برمجيات خدمية',
  payments: 'مدفوعات إلكترونية',
  egypt: 'مصر',
  syria: 'سوريا',
  ksa: 'السعودية',
  'saudi arabia': 'السعودية',
  contech: 'تكنولوجيا الإنشاءات',
  procurement: 'مشتريات وتوريد',
  govtech: 'تقنية حكومية',
  public: 'قطاع عام',
  hydrogen: 'هيدروجين',
  'hajj-umrah': 'حج وعمرة',
  'travel-tech': 'تكنولوجيا السفر',
  tourism: 'سياحة',
  delivery: 'توصيل وطلبات',
  cxm: 'تجربة العملاء',
  education: 'تعليم',
  foodtech: 'تكنولوجيا الأغذية',
  closed: 'شركات مغلقة',
  bnpl: 'اشترِ الآن وادفع لاحقًا',
  communications: 'اتصالات ومراسلات',
  'retail-tech': 'تكنولوجيا التجزئة',
  enablement: 'تمكين التجارة',
  qatar: 'قطر',
  media: 'إعلام',
  turkey: 'تركيا',
  gaming: 'ألعاب إلكترونية',
  'sports-tech': 'تكنولوجيا الرياضة',
  'assistive-tech': 'تقنية مساعدة',
  aviation: 'الطيران',
  climatetech: 'تكنولوجيا المناخ',
  'food-security': 'أمن غذائي',
  idea: 'مرحلة الفكرة',
  frontier: 'أفكار رائدة',
  japan: 'اليابان',
  uae: 'الإمارات',
  jordan: 'الأردن',
  china: 'الصين',
  'south-korea': 'كوريا الجنوبية',
  singapore: 'سنغافورة',
  biotech: 'تكنولوجيا حيوية',
  semiconductors: 'أشباه الموصلات',
  ev: 'سيارات كهربائية',
  palestine: 'فلسطين',
  'occupied-palestine': 'فلسطين المحتلة',
  indonesia: 'إندونيسيا',
  kuwait: 'الكويت',
  india: 'الهند',
  nigeria: 'نيجيريا',
  iran: 'إيران',
  lebanon: 'لبنان',
  canada: 'كندا',
  agrifood: 'أغذية وزراعة',
  manufacturing: 'تصنيع',
  uk: 'المملكة المتحدة',
  'united kingdom': 'المملكة المتحدة',
  usa: 'الولايات المتحدة',
  'united states': 'الولايات المتحدة',
  switzerland: 'سويسرا',
  germany: 'ألمانيا',
  france: 'فرنسا',
  robotics: 'روبوتات',
  space: 'فضاء',
};

// Tags that denote a country, not a sector/theme. The /tags index renders
// these in a separate "Countries" section with its own shape so they never
// share the sector sticker-cloud look.
export const countryTags = new Set([
  'egypt',
  'syria',
  'ksa',
  'saudi arabia',
  'qatar',
  'turkey',
  'uae',
  'japan',
  'jordan',
  'china',
  'south-korea',
  'singapore',
  'palestine',
  'occupied-palestine',
  'indonesia',
  'kuwait',
  'india',
  'nigeria',
  'iran',
  'lebanon',
  'canada',
  'uk',
  'united kingdom',
  'usa',
  'united states',
  'switzerland',
  'germany',
  'france',
]);

export const countryFlagMap: Record<string, string> = {
  egypt: '🇪🇬',
  syria: '🇸🇾',
  ksa: '🇸🇦',
  'saudi arabia': '🇸🇦',
  qatar: '🇶🇦',
  turkey: '🇹🇷',
  uae: '🇦🇪',
  japan: '🇯🇵',
  jordan: '🇯🇴',
  china: '🇨🇳',
  'south-korea': '🇰🇷',
  singapore: '🇸🇬',
  palestine: '🇵🇸',
  'occupied-palestine': '🇵🇸',
  indonesia: '🇮🇩',
  kuwait: '🇰🇼',
  india: '🇮🇳',
  nigeria: '🇳🇬',
  iran: '🇮🇷',
  lebanon: '🇱🇧',
  canada: '🇨🇦',
  uk: '🇬🇧',
  'united kingdom': '🇬🇧',
  usa: '🇺🇸',
  'united states': '🇺🇸',
  switzerland: '🇨🇭',
  germany: '🇩🇪',
  france: '🇫🇷',
};

// Display English name per country tag (tags use short codes like ksa/uae).
export const countryEnMap: Record<string, string> = {
  egypt: 'Egypt',
  syria: 'Syria',
  ksa: 'Saudi Arabia',
  'saudi arabia': 'Saudi Arabia',
  qatar: 'Qatar',
  turkey: 'Turkey',
  uae: 'United Arab Emirates',
  japan: 'Japan',
  jordan: 'Jordan',
  china: 'China',
  'south-korea': 'South Korea',
  palestine: 'Palestine',
  'occupied-palestine': 'Occupied Palestine',
  kuwait: 'Kuwait',
  singapore: 'Singapore',
  indonesia: 'Indonesia',
  india: 'India',
  nigeria: 'Nigeria',
  iran: 'Iran',
  lebanon: 'Lebanon',
  canada: 'Canada',
  uk: 'United Kingdom',
  'united kingdom': 'United Kingdom',
  usa: 'United States',
  'united states': 'United States',
  switzerland: 'Switzerland',
  germany: 'Germany',
  france: 'France',
};

// Country cards on /tags share ONE uniform accent (set in
// src/pages/tags/index.astro). No per-country color map: a hue must encode
// something real (status does on idea cards), and country hues encoded
// nothing while colliding with the status meanings.
